### ISSUE TITLE
Support something simliar to context

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#122]
https://taskwarrior.org/docs/context.html

@srfraser mentioned in another issue that it would be handy to be able to dynamically determine contextual information from the current directory, and by running external commands.  Is there a general approach we could take here?

**Comment by srfraser** [comment]
Straightening things out in my own head, there are several angles:

1. Manually setting a context as taskwarrior does, or dynamically generating it, or both
2. How taskchampion expects to receive this context - flags, tags, k:v pairs - some idea of how they'd be implemented might give clues about how to communicate them
3. If dynamic, how to determine that data
   a. Tools such as https://github.com/direnv/direnv 
   b. We could try and be clever about the directory we're in and discover `.git` `.hg` directories
   c. The config file could allow a script to be set, that will be run on modification commands to generate appropriate flags

**Comment by djmitche** [comment]
I think we want to avoid baking specific interfaces like git and hg into the tool -- that opens the door to a slew of follow-on PRs to add more functionality and creeping growth.  And inevitably privileges some integrations over others.  Do we add a Darcs interface?  SourceSafe?  BitKeepr?  etc.

I suspect some careful planning could generate a kind of "hook" interface that can support this.  We've got time to design something nice here.

**Comment by savchenko** [comment]
There is lively conversation about contexts: https://github.com/taskchampion/taskchampion/discussions/163, pending its resolution.
