### ISSUE TITLE
Allow modifying status with `status:..`

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#134]
There's a `status:..` filter expression.  Add a similar modification.

**Comment by savchenko** [comment]
It seems like it is very much possible to set status en masse: https://github.com/taskchampion/taskchampion/issues/213

**Comment by djmitche** [comment]
There is a `done` command that sets `status` to `done`, but for example no way to set a task back to pending.  This would allow that with
```
ta modify 13 status:pending
```
