### ISSUE TITLE
Automatically document built-in reports

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#137]
Just like we do for filters and modifications, let's build some automatic documentation for the built-in report formats.

**Comment by savchenko** [comment]
Including them in `--help` might be a good idea. `ta --help | igrep -C1 report`
```
task [filter] [report-name] *or* [report-name] [filter]
    Show the named report, including only tasks matching the filter
task [filter]
    Show the report named 'next', including only tasks matching the filter
```
Even a simple list of valid values for the "report" would be good.
