### ISSUE TITLE
Better documentation for configuring a sync server

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#158]
https://djmitche.github.io/taskchampion/task-sync.html doesn't really say how to set up synchronization for a replica.  It mentions `server_origin`, but not how to get that value.  Let's improve that, so that someone knows what information to ask for from a sync server operator, or to figure out from their own sync server setup.

**Comment by savchenko** [comment]
Tagging as [TBD](https://github.com/taskchampion/taskchampion/labels/TBD) while this is waiting on #175
