### ISSUE TITLE
Allow machine-readable import & export

### ISSUE THREAD

**Issue by savchenko** [GothenburgBitFactory/taskchampion#173]
Based on https://github.com/djmitche/taskchampion/issues/159, shall we narrow-down the scope to a single machine-readable export that can be passed to an arbitrary tool?

As an example:

- `ta export tasks` &mdash; dumps all tasks into stdout wrapped in JSON.

**Comment by djmitche** [comment]
Yeah, that seems reasonable. More sophisticated uses should use their own Replica, but lots of simpler uses can be accomplished with an export.

**Comment by savchenko** [comment]
@dbr / @djmitche , is this a "tick" (large change) or "tock" (lesser thing)? Judging by the amount of work necessary.

**Comment by dbr** [comment]
I would suspect more towards the largest side of things - the actual output of tasks as JSON or whatever is easy (tasks are already serializable as JSON), but making sure the output is as we want, documented, and tested to ensure stability of output will take a bit of time and thought

**Comment by savchenko** [comment]
Thanks. Moved under v0.9.0 which translates into _"aiming to get it done before the release, but without any particular urgency"_.

**Comment by djmitche** [comment]
Per discussion in #162, let's include an `ta import tasks` at the same time that will import the same format.  Then users can transform or generate that format.
