### ISSUE TITLE
Return `taskchampion::Error` from Replica API

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#226]
There's a public Error type defined, but none of the API methods actually return it.  Some of the returns could be *downcast* to this type, but that's not really useful.

* Change all replica API methods to return `Result<_, taskchampion::Error>`
* Add an `Other` variant to that type that can contain an `anyhow::Error`
* Consider adding a few other variants that might be useful to callers of the API.

**Comment by savchenko** [comment]
Same milestone as https://github.com/taskchampion/taskchampion/issues/217
