### ISSUE TITLE
Investigate neater options for styling terminal text

### ISSUE THREAD

**Issue by dbr** [GothenburgBitFactory/taskchampion#229]
As mentioned in #228 termcolor makes the code for outputting text quite verbose and obscures the actual content. Since it'll be quite a common thing, could we have a simple wrapper around `termcolor` which helps make format strings intermixed with styling neater?

**Comment by dbr** [comment]
As an "unreasonable benchmark":

```rust
write!(w, "Set configuration value {} in {:?}", &key, filename)
```

..and using raw termcolor:
```rust
write!(w, "Set configuration value ")?;
w.set_color(ColorSpec::new().set_bold(true))?;
write!(w, "{}", &key)?;
w.set_color(ColorSpec::new().set_bold(false))?;
write!(w, " in ")?;
w.set_color(ColorSpec::new().set_bold(true))?;
write!(w, "{:?}.\n", filename)?;
```

On a quick search I found a few options - haven't tested any, just based on what is in their README/docs:

## `termcolor_output`

https://docs.rs/termcolor_output/1.0.1/termcolor_output/macro.colored.html

```rust
colored!(
    writer,
    "Set configuration value {}{}{} in {}{}{}",
    bold!(true), &key, bold!(false),
    bold!(true), filename, bold!(false),
).unwrap();
```

I think this makes the format string easier to read, but the arguments are a bit cluttered. Impressively has a 1.x release!

Maybe using named arguments (if supported) like `{bold}{key}{boldoff}` etc would improve things

## `burnt`

https://docs.rs/bunt/0.2.4/bunt/

```rust
bunt::writeln!(w, "Set configuration value {[bold]} in {[bold]:?}", &key, filename);
```

This looks a lot nicer, and makes adding additional colouring etc not require any additional format args

**Comment by djmitche** [comment]
`burnt` looks a lot like Python's `blessings` which IMHO has a really nice API.
