### ISSUE TITLE
Terminal UI

### ISSUE THREAD

**Issue by dbr** [GothenburgBitFactory/taskchampion#258]
Possibly a large rabbit-hole, but there is [`taskwarrior-tui`](https://github.com/kdheepak/taskwarrior-tui), a interactive UI for taskwarrior, which is written in Rust.

On a very quick skim of the code it seems to be very closely coupled to taskwarrior via subprocess calls, so most certainly not a trivial thing to adapt to TC (especially given we aren't aiming to be 1:1 compatible with TW), and if anyone ever did this, it most probably it would be easier to use the taskwarrior-tui as inspiration and write a new thing from ~scratch

**Comment by djmitche** [comment]
I agree a rewrite is probably in order.  I'll make a new "integrations" label for this, as it would be best implemented as a separate project that consumes the Replica API.

**Comment by kdheepak** [comment]
I just stumbled onto this project, great work! 

I’m the author of `taskwarrior-tui`, and I’m planning to refactor / rewrite `taskwarrior-tui` ( too much technical debt from initial design decisions ) and in that process I could make the source configurable and explore how it could use  `taskchampion` optionally. I haven’t fully explored this project fully yet but I think if the “backend” is abstracted it would work well.

**Comment by djmitche** [comment]
That's too cool -- I didn't realize that taskwarrior-tui was in Rust!  There's definitely room to collaborate here, but maybe not how you're imagining?

At the moment, I'm working on rewriting TaskWarrior's sync system ("replicas" talking to a "sync-server") to match that of TaskChampion, while simultaneously working on making TaskChampion's data model (mostly: how task properties are interpreted) to match TaskWarrior.

If I'm successful, then both tools will be able to interoperate.  We will likely abandon the TC CLI, as it's got a _long_ way to go to be as expressive as TaskWarrior's.  That will leave:
 * a single sync server implementation
 * a combined implementation of a replica and a great CLI (TaskWarrior)
 * a language-level replica API (TaskChampion)

At that point, you could rewrite taskwarrior-tui to use the replica API to manage its own replica, and sync that with a user's other replicas using the normal sync machinery.

What do you think?

(I'd like to use some FFI to make the replica API available to non-Rust apps, but that can come later..)

**Comment by kdheepak** [comment]
That sounds like a plan! I don't know when I'll be tackling this refactor, but I don't imagine it'll be very soon. I'll track this issue and the project for updates too, and I'll share updates here once I get to that task.

**Comment by djmitche** [comment]
Sounds good!  In the interim, if you want to help out with TC that'd be appreciated.  https://github.com/taskchampion/taskchampion/milestone/2 is the near-term plan..

**Comment by kdheepak** [comment]
Have you considered using https://git.sr.ht/~matthiasbeyer/task-hookrs for the data model?

**Comment by djmitche** [comment]
Have a look at the TC code :)
