### ISSUE TITLE
Language bindings

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#259]
The various integrations we'd like to build would require convenient bindings for the Replica API in other languages.  For mobile, I think we would need Java, but maybe we could get away with JS bindings to a WASM build?  For various scripting interfaces, we'd want Python (or maybe Ruby?).  C#?  Swift?

**Comment by dbr** [comment]
Not sure if it's a good approach for TC, but one approach I've seen work well for various things around the [`imgui`](https://github.com/ocornut/imgui) ecosystem is to just provide a reasonable C API ([`cimgui`](https://github.com/cimgui/cimgui)). Writing language specific bindings to these can done for most languages without too much trouble

That said, I've also used [`pyo3`](https://github.com/PyO3/pyo3) and it makes exposing Rust code to Python quite remarkably easy, not sure if similar projects exist for other languages

**Comment by djmitche** [comment]
https://github.com/taskchampion/taskchampion/issues/333 covers the C API, but I'll leave this open for building onto that for other languages.
