### ISSUE TITLE
Use connection pooling in SQLite server storage

### ISSUE THREAD

**Issue by dbr** [GothenburgBitFactory/taskchampion#278]
As per discussion here https://github.com/taskchampion/taskchampion/pull/206#issuecomment-860851778

Currently (for 0.4.0 release) a new SQLite connection is made for each operation which isn't too efficient. Instead the `r2d2` crate or similar can be used to have a pool of connections

It's a bit hard to guess how worthwhile this change is - the performance with creating lots of connections is likely perfectly adequate even with a vague "handful" of users; and anyone aiming to run a server for more than that probably wants to implement a more appropriate storage backend anyway (e.g Postgres/Redis/etc)

**Comment by djmitche** [comment]
I think the main reason to do this would be to provide a better example for future use of other DB backends, using the same approach (r2d2 supports multiple backends).

**Comment by dbr** [comment]
Ah yeh that's a good point!

I guess the other option would be to use something more all-encompassing like https://github.com/diesel-rs/diesel which abstracts away the specific query DB library also (so same connection implementation would work for sqlite and postgres), and also gives things like schema migrations.. but seems like a much heavier option dependency-wise
