### ISSUE TITLE
Document encryption properties

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#302]
We had this in the README:

https://github.com/taskchampion/taskchampion/commit/636862f8c5606bb9969c6bbeea8182c9a2e3ccc4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L24
```
 * Reasonable privacy: user's task details not visible on server
```

but that's not very detailed.  Let's write a better description in the docs.

@savchenko what would that look like -- do you have an example?

**Comment by savchenko** [comment]
@djmitche I do, but need to finish the current "sprint" or face the wrath of @dbr whom I'd rather not disappoint. 
If this isn't urgent, please feel free to assign me and I will contemplate on this afterwards.
