### ISSUE TITLE
run C bindings via valgrind in CI

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#337]
See @dbr's comment in https://github.com/taskchampion/taskchampion/pull/332#issuecomment-1057580024 for how this was run manually.

**Comment by dbr** [comment]
Haven't tested but https://github.com/jfrimmel/cargo-valgrind seems pretty good from a skim of it's source

Only minor issue is the project doesn't seem to include prebuilt binaries (but it barely has any dependencies so should build quickly, and we can just cache the install via the GH Actions cache step)

**Comment by djmitche** [comment]
Nice find!  My googling around suggested it required a lot more setup than that :)

**Comment by djmitche** [comment]
With #409, This is no longer a useful idea in this repo.
