### ISSUE TITLE
Allow sync origins containing paths

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#367]
From GothenburgBitFactory/taskwarrior#3361, we should allow the sync server to be configured by URL, not just origin. This will require
 * changing the name of the `sync.server.origin` config to `sync.server.url`, but keeping backward compatibility
 * parse it as a URL, and generate the paths for the various requests by appending to the configured path

This will involve some minor changes in `taskchampion/taskchampion/src/server/sync/mod.rs` as well as updating everywhere that `sync.server.origin` occurs to prefer `sync.server.url`.

**Comment by dahelb** [comment]
I'd like to give this a try :) !

**Comment by djmitche** [comment]
Great! In this repo, I think we'll want to update
https://github.com/GothenburgBitFactory/taskchampion/blob/5168f0b86415826aa84f70d1e072b6364dd431aa/taskchampion/src/server/config.rs#L23-L33
to use `url` instead of `origin` but still as type `String`. Then follow the compiler errors to everywhere that's set or used. Within 
https://github.com/GothenburgBitFactory/taskchampion/blob/5168f0b86415826aa84f70d1e072b6364dd431aa/taskchampion/src/server/sync/mod.rs#L12-L17
you can store an actual `Url` type, and then append to the path on that URL as needed elsewhere in that file.

This will be a breaking change to the library, and there will be some follow-up in the Taskwarrior repo to accommodate it, but that's OK. I expect a few breaking changes in the short term.

**Comment by djmitche** [comment]
Nice work on this! The work on the Taskwarrior side will require the remainder of GothenburgBitFactory/taskwarrior#3209 - using TC as an external dependency.
