### ISSUE TITLE
Sync to AWS

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#368]
Similar to the GCP sync implemented in GothenburgBitFactory/taskwarrior#3185, we should be able to sync replicas to AWS's object storage.

The tricky bit here is that, unlike GCS and Azure Blob, S3 does not provide a compare-and-swap operation.

Some reading suggests that the easiest way to accomplish this would be to use DynamoDB as a lock over the "latest" object in the S3 bucket.

**Comment by dathanb** [comment]
As of August 20, AWS S3 [now supports conditional writes](https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/), so I think this should be doable with bare S3 without needing additional coordination via Dynamo.

**Comment by djmitche** [comment]
Wow, new features in an 18-year old product!

It looks like this only supports checking whether a file exists, not whether it has been changed, so might require some additional work to figure out how to get the update-if-not-changed behavior we need.

**Comment by dathanb** [comment]
I haven't checked the sync protocol -- does it support any sort of pessimistic locking around the sync operation? If so, the AWS integration code could identify an object key that acts as a semaphore, and sync will only succeed if the client can acquire the semahpore / do a conditional put to that object. (Also as part of the initial setup a bucket would need to be configured for the semaphore object ot live in, and the bucket policy should have a TTL set so the object will automatically expire after some amount of time, to recover from the case where a client fails to release the semahpore / fails to delete the object.)

**Comment by djmitche** [comment]
That could work! The only bit that needs synchronization is `latest`, in a kind of test-and-swap fashion.

https://github.com/GothenburgBitFactory/taskchampion/blob/c7c2cde0e6b7cb34f4fa307c1b8817af760dd184/taskchampion/src/server/cloud/service.rs#L30-L37

The locking could occur around that operation.

**Comment by dathanb** [comment]
Oh yeah, we can totally use pessimistic locking to implement compare-and-swap. 👍 Lemme see if I can carve out some time to work on that.

**Comment by travisby** [comment]
https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-s3-functionality-conditional-writes/ might simplify the plan here!

**Comment by djmitche** [comment]
Oh, that's great news!

**Comment by djmitche** [comment]
WIP - https://github.com/GothenburgBitFactory/taskchampion/pull/492
