### ISSUE TITLE
Reconsider "level" of the Task/TaskMut interface

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#372]
The problem that brought me [to GothenburgBitFactory/taskwarrior#3029] is, Taskwarrior _mostly_ doesn't call functions like `set_description` or `add_annotation` -- it interfaces directly with the key/value pairs that make up a task, via `set_value`.  But it does call `set_status` since that updates the working set.  So the issue was that Taskwarrior would call

 * `t.set_value("modified", "12345")`
 * `t.set_status(Status::Pending)`

and the second call would not "see" that the modified timestamp had already been set, and would do so again.  On import, this causes a problem by setting the "modified" timestamp of all tasks to the time the import occurred.

Overall, this is a major "impedance mismatch" between TC and TW: TW wants to handle tasks as key/value maps, while TC was really designed for API consumers to call methods that embody more knowledge about the meaning of particular keys.  These are more than just convenience wrappers, though: they also have this set-the-modified-timestamp thing, as well as automatically updating the working set.  And (referring to GothenburgBitFactory/taskwarrior#3028) it might be good to cache parent/child relationships as well, to avoid having to load most of the pending tasks one-by-one.  I've been mulling this over for a while but haven't come up with a concrete way to do better.

_Originally posted by @djmitche in https://github.com/GothenburgBitFactory/taskwarrior/issues/3029#issuecomment-1414569579_

**Comment by djmitche** [comment]
I've gotten a start to this now, in #413. I'll leave some notes here that I will probably return to and update later.

## Notes

### General Goal

 * Tasks can be read and queried, with tasks represented as a simple wrapper around a HashMap.
 * Changes to tasks are represented as `Operation` instances, collected in an `Operations` type that is a thin wrapper around `Vec<Operation>`. New operations can be created in a variety of ways such as `Replica::new_task`, `Task::set_property`, or `Task::delete`, all of which take `&mut Operations`. (Note that this is, in essence, #373)
 * Operations are "committed" to the task DB by passing the `Operations` to a Replica method.
 * All of this blends nicely with the current undo support: the latest batch of undo operations are represented as `Operations`, and committing that undo involves reversing the operations and committing the result, with an optimization of "popping" matching operations from the DB's operations (as happens now).

### Complications

 * `taskdb::apply`, which is basically the "commit" operation above, currently takes a SyncOp and creates an Operation from it. An Operation contains the information in a SyncOp but also undo-related information. Maybe it is more precise to capture this undo-related information at the time that the change is committed, but that would mean throwing out any undo-related information provided during the accumulation of the `Operations`.
 * Replica will need to keep its working set up to date based on the operations it applies.
 * Ideally the existing higher-level `Task` API would also stick around -- or something like it -- for users that want to operate at that higher level. For example, an Android app for adding new tasks on voice command probably doesn't want to be bothered with how the `modified` property is encoded. It just wants to call something like `replica.add_task()` and then `task.set_description()`, etc. and have everything work out.

### Use by Taskwarrior

For read-only purposes, TW's `Task` mirrors the first bullet point above: they are little more than `std::map <std::string, std::string> data`. So, they could easily be adjusted to contain a tc::Task representing the same thing.

The existing `TDB2::modify` method takes a Task, compares it to the one in the DB, and makes the necessary changes such that the DB matches the given Task. If `Task` carries an `Operations` recording the changes made to it, then `TDB2::modify` would just be committing those changes.

All of the other operations are more immediate: deleting, creating, etc. Those can be accomplished by creating the necessary operations and immediately committing them.

**Comment by djmitche** [comment]
A bit more progress now. I think we can do this without breaking changes to the public API, and I'd like to get that merged first (it will be split over a few PRs).

Once that's done, I think we can actually do a much better job with the "high-level" API, too. Since nothing really uses those, I think this is a good time to break them.

**Comment by djmitche** [comment]
The sequence of PRs I've got in https://github.com/GothenburgBitFactory/taskchampion/compare/main...djmitche:taskchampion:issue372-operations ends up creating a new `BasicTask` that just exposes getters and setters, with the setters generating a sequence of Operations that can later be committed. The existing functionality (Task, TaskMut and Replica functions like `delete_task`) are all rewritten in terms of this new type, without breaking API changes (I thope!).

I'm not sure what to do next. I kind of dislike the name BasicTask and would like to just have one Task type. But, I'd also like to have a clear distinction between low-level and high-level functionality in the generated docs. A few ideas I've had:

 * Keep BasicTask but modify the existing high-level TaskMut methods to generate operations, e.g., `task.set_status(Status::Completed, &mut ops)` and move them to the Task type. This would be a breaking API change, but keeps the high-level interface while allowing multiple operations to be batched into a single transaction. However, it still has two task types (BasicTask and Task)
 * Rename BasicTask to Task, and implement the high-level methods in a trait like HighLevelTask - basically an ["extension trait"](https://github.com/rust-lang/rfcs/blob/26197104b7bb9a5a35db243d639aee6e46d35d75/text/0445-extension-trait-conventions.md). This would separate those methods nicely in the docs, but is otherwise kind of a hack.
 * Just merge BasicTask and Task and TaskMut and include some preliminary text in the docstring to describe the low- and high-level interfaces.

I'm open to opinions or other ideas!

**Comment by ryneeverett** [comment]
Another idea, though I doubt it is better:

- Make `Task` a wrapper around `BasicTask` by replacing the `uuid` and `taskmap` properties with a single `basictask` property and implementing the higher level interface entirely by using the lower level interface. If you wanted to expose the low-level interface also you could define the property as `pub basictask`.

*Edit:* Reflecting on this a bit more, I think I can make a case that this option has many of the benefits of the other options without the drawbacks:

- Like the first option, Task ends up defined in terms of operations, but vicariously rather than a parallel implementation.
- Like the second option, we get DRYness and unity, but through composition rather than "kind of a hack".
- Like the third option, the low-level interface is available on the same type as the high-level interface, but rather than depending on docstrings this would be communicated by accessing methods on the basictask property.

**Comment by djmitche** [comment]
That makes a lot of sense - thanks! I appreciate your careful thought about this.

**Comment by djmitche** [comment]
Current status: this is largely finished in taskchampion, and I'm working on building the FFI interface using https://cxx.rs in Taskwarrior. That's already led to a few relatively minor local changes in TC, and may generate a few more, Once I've got all of that working I'll put the changes up for review.
