### ISSUE TITLE
Add support for purging tasks

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#383]
..meaning actually removing them from the task DB. This already occurs when tasks expire (#341), but sometimes (https://github.com/GothenburgBitFactory/taskwarrior/issues/3399) users want to purge a task without waiting for expiration.

It's OK for this to break the sync model a little bit, as long as that's clear in the documentation.  #26 has some discussion of this.

**Comment by djmitche** [comment]
This is referring to purging specific tasks before they expire -- not the existing `Replica::expire_tasks` support.

**Comment by djmitche** [comment]
@QuantumBJump would this be an interesting task for you to work on?

**Comment by QuantumBJump** [comment]
I'll have a looksee, can't promise anything so don't assign yet, but I'll get back to you :)

**Comment by djmitche** [comment]
#405 should do for this repo. @QuantumBJump I forgot there's already a method for this -- I just had to make it public!

Once that's done, I think we can release 0.6.0 and then implement this (and the server URL) in Taskwarrior.
