### ISSUE TITLE
Feature: Support .corn for configuration instead of TOML

### ISSUE THREAD

**Issue by izelnakri** [GothenburgBitFactory/taskchampion#389]
Considering most software is moving to nix/nix-like configuration expressions and many features nix has compared to TOML. I suggest moving the default configuration format of `taskchampion` to `cornlang`. It is a subset of nix that seems to be done with right trade-offs: https://cornlang.dev/

This will result in:
- less duplication due to support of variables etc.
- more flexible expression, less errors configuration gets done
- Pathway to Pkl configuration language when Pkl becomes mature, this could provide the best documentation experience with types.
- Easier to read/consume configuration(this one is in my opinion, subjective).

**Comment by djmitche** [comment]
Which configuration are you referring to?

**Comment by izelnakri** [comment]
[~/.config/taskchampion.toml](https://gothenburgbitfactory.org/taskchampion/config-file.html) . There seems to be also inconsistency in the docs, 2 different files are mentioned: [taskchampion.toml](https://gothenburgbitfactory.org/taskchampion/config-file.html) and [taskchamption.yaml](https://gothenburgbitfactory.org/taskchampion/welcome.html#synchronizing) Seems like both are same files and the binary can use different ones(with some priority order), this is a good feature however ideally the documentation should mention one for consistency, could also mention that it supports different formats.

**Comment by ryneeverett** [comment]
IMO there would need to be a more concrete value offered to taskchampion to adopt a dependency with a README that states:

> At the moment Corn is in very early stages.

**Comment by djmitche** [comment]
Ah, we need to update those docs. There is no `ta` command anymore, and thus nothing to read a config file, so no need to decide on a format for that file. So, nothing to do here!
