### ISSUE TITLE
Replace `set!` with `HashSet::from`

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#415]
The comment at the top was written when we were still compatible with Rust < 1.56. The current MSRV is 1.70, so we can now use `HashSet::from` and get rid of this macro.

https://github.com/GothenburgBitFactory/taskchampion/blob/e725a38c991dd32fd5f3b9b2daa4644b7dbbc9d2/taskchampion/src/macros.rs#L3-L17

**Comment by koleesch** [comment]
I'll take this ticket

**Comment by koleesch** [comment]
It is currently open.

**Comment by djmitche** [comment]
Oops!
