### ISSUE TITLE
Disable pre-commit.ci for this repo

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#432]
This repo already has workflows for formatting and checking. Is it possible to restrict the repos for which pre-commit.ci runs?

cc @tbabej and @felixschurk !

**Comment by djmitche** [comment]
See https://github.com/GothenburgBitFactory/taskchampion/pull/431 where this workflow ran but failed due to not having any config.

**Comment by felixschurk** [comment]
Huh, that should not be the case - however it should be easy to do so for an Organisation owner.

![image](https://github.com/user-attachments/assets/5d3b570b-746e-4257-9601-c2387f9480ff)

Going to https://pre-commit.ci/ -> Sign in with GitHub -> Manage Repos on GitHub.
