### ISSUE TITLE
Add `Replica::pending_tasks` and `pending_task_data`

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#452]
We already have [`Replica::all_tasks`](https://docs.rs/taskchampion/latest/taskchampion/struct.Replica.html#method.all_tasks) and [`all_task_data`](https://docs.rs/taskchampion/latest/taskchampion/struct.Replica.html#method.all_task_data), so it may make sense to add `Replica::pending_tasks` and `pending_task_data` which could then join on the working_set table (as opposed to taking an arbitrary list of UUIDs).

I suspect the implementation of this would be relatively straightforward, and based on existing examples at both the `Replica` and underlying `TaskDB` levels in TaskChampion. The connection to C++ is now much simpler than it used to be, [using cxx](https://github.com/GothenburgBitFactory/taskwarrior/blob/72f9cd91a519034b592fc3069da1e764776a203b/src/taskchampion-cpp/src/lib.rs), so that should also be relatively straightforward. And then calling the result from TDB2 is also pretty easy. The tricky bit is implementing it in TaskChampion and then developing against that in Taskwarrior, since they are different repos -- but I can help with that. This is definitely worth doing even if it's not the biggest contributor to poor performance. Do you want to give it a shot? If so, let's open a new issue to track the work.

_Originally posted by @djmitche in https://github.com/GothenburgBitFactory/taskwarrior/issues/3329#issuecomment-2335007219_

**Comment by Scandiravian** [comment]
Hey @djmitche,

I've started looking into this and have written a simple implementation of `pending_tasks` with the signature `pub fn pending_tasks(&mut self) -> Result<Vec<Task>> `. This was to match this part of the cpp function: https://github.com/GothenburgBitFactory/taskwarrior/blob/40ea3f2f5418ab5795e2aa0e73a1206c1d18cc1e/src/TDB2.cpp#L355-L367

I'm not entirely sure this is the way you'd prefer it was done, so I'd like to open a draft so you can have a look before I start on the `pending_task_data` function if that's alright with you?

**Comment by djmitche** [comment]
Sure, that sounds great!

**Comment by metent** [comment]
Hi @djmitche, I am planning to incorporate taskchampion for my tasks app. I was reading through taskchampion's docs and source code when I noticed the lack of a function which returns tasks based on an applied filter. I skimmed through taskwarrior's source to see how they implemented it and I believe they iterate through all tasks and check if each task satisfy the criteria rather than running an sqlite query.

Is this the intended way to implement filtering, or like `Replica::pending_tasks`, are Replica methods for implementing filtering planned to be added in a future release?

**Comment by djmitche** [comment]
The intended way is to select either `Replica::pending_tasks` or `Replica::all_tasks` and then filter from there. The idea is that especially the set of pending tasks is usually quite small, so it's easiest to just iterate over all tasks and match the required conditions, rather than find a way to represent all conditions in some programmatic way to be evaluated by the storage backend.

**Comment by djmitche** [comment]
@Scandiravian did you want to make the relevant changes in Taskwarrior, as well (basically making these new Replica methods available in C++ and calling them in TDB2::pending_tasks)? That will require a little bit of coordination, since we will need to release a new version of Taskchampion first. And, I have things in a bit of an unstable state with #373, so that may take a little bit.

**Comment by Scandiravian** [comment]
> @Scandiravian did you want to make the relevant changes in Taskwarrior, as well (basically making these new Replica methods available in C++ and calling them in TDB2::pending_tasks)? That will require a little bit of coordination, since we will need to release a new version of Taskchampion first. And, I have things in a bit of an unstable state with #373, so that may take a little bit.

@djmitche I haven't coded C++ in more than a decade, so it depends on the complexity of the change. If it's simple, such as replacing method calls, I can probably figure it out; I'm happy to give it a go at least

I'm going to be away on holiday until the middle of next week, so won't be able to start work on the C++ code until then. Is that alright with you?

**Comment by djmitche** [comment]
When I started working on Chromium almost 2 years ago, I felt the same way -- I hadn't done C++ since 2000! I'm sad to report a decade hasn't done it any favors..

That timing sounds fine. Maybe I can finish up #373 by then!

**Comment by djmitche** [comment]
@Scandiravian were you going to have a chance to work on this?

**Comment by djmitche** [comment]
Oh, sorry, #3632 is the work on that - we can follow up there.
