### ISSUE TITLE
Publicize this effort

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#52]
Once there's an MVP for this project, we'll want to get people in to start using it and start hacking on it.  That means talking about it in public.
 * Blog post highlighting it
 * Posts on Reddit?
 * Posts on Twitter?
 * Posts on Hackernews?
 * Posts on .. whatever?

I can do the blog post, but I'm not a big participant in the social corners of software engineering, and I'm not on any of the social apps listed above.  So *I will need some help here!*

**Comment by bbigras** [comment]
> Once there's an MVP for this project, we'll want to get people in to start using it and start hacking on it.

Do you mean only for devs?

Since the README has the following, I'm wondering if it's a good idea or not to package taskchampion in distros:

> While you are welcome to [help out](https://github.com/taskchampion/taskchampion/blob/main/CONTRIBUTING.md), you should do so with the awareness that your work might never be used. But, if you just want to get some practice with Rust, we'd be happy to have you.

> TaskChampion currently functions as a "testbed" for new functionality that may later be incorporated into TaskWarrior. 

Is Taskwarrior planning to provide encryption at rest for their server anytime soon? Because I see taskchampion's support of this feature a big plus.

**Comment by djmitche** [comment]
Hi!  This issue was originally written when progress on TaskWarrior had been stalled for years, and the intent was to build TaskChampion into a replacement for it.  Shortly afterward, work on TW began again and we re-focused TC's purpose, first to a "test lab" for future TW functionality and more recently as a "core" for the existing TW CLI support, which would have the effect of providing at-rest encryption for sync data.  That work is [in progress](https://github.com/orgs/GothenburgBitFactory/projects/2), but largely by me and @dbr and thus not moving particularly fast.  And, I haven't written C++ since maybe 1999 so I'm having to (re)learn a lot of its peculiarities.

Any ideas on how to get more bandwidth on that project are welcome :)

I don't think packaging TC as-is in distros is a good idea -- its CLI is incomplete, and until the 1.0 release its compatibility guarantees are minimal.
