### ISSUE TITLE
Implement due dates

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#82]
This would just be a "due" property on tasks, and some nice ways of filtering on that field.

**Comment by djmitche** [comment]
I think this will require amending the filter functionality to support comparisons.  In TW that's things like `due.after:2020-05-28`, but we could use more "expression-y" syntax like `due > 2020-05-28`.

There's more thinking to do there over types in the expression language -- does `due > 2020-05-28` parse differently than `description > 2020-05-28`, since `due` and `description` have different types?

**Comment by dbr** [comment]
What does "due after" mean (I don't understand how it would differ from just "due")

**Comment by djmitche** [comment]
"due after x" means `due > X`.  "due X" means `due == X`.  I think `due.before` or `due < X` would be more common, really, to find tasks that are "past due".
