### ISSUE TITLE
Implement urgency

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#87]
TaskWarrior has a pretty sophisticated way of calculating, and sorting by, urgency.  Let's implement something similar.

**Comment by savchenko** [comment]
Dependencies aside, perhaps calculating _"when task was touched last time and for how long it has existed prior to that"_ would be a good v1?

**Comment by djmitche** [comment]
Yeah, and doing that in a way that the urgency calculation is implemented abstractly, so that we can replace it later, would do the trick.

**Comment by djmitche** [comment]
I think this should be in the CLI, as (a) it has configuration and (b) that's how TW does it.

We might _later_ decide to have a way of implementing configuration within the taskdb, in which case we could make this part of the data model.
