### ISSUE TITLE
Build an Android app

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskchampion#93]
It'd be swell to have an Android app that acts as a replica.  The "TaskWarrior for Android" app is actually a great design for this.  It's interactive, but still sticks close to the command-line-tool nature of TaskWarrior.

Once nice bonus is that we don't need to ship an executable and shell out to it -- just link the Rust and Java using FFI.

**Comment by bbigras** [comment]
Any APK or download link?

**Comment by djmitche** [comment]
Oh, sorry to get your hopes up - this was closed after migrating from the archived taskchampion repo. It'd be great to have an Android app, but it wouldn't be built in this repo.

I forgot GitHub has closed reasons. I'll fix this one ..

**Comment by djmitche** [comment]
(FWIW I really want an Android app too! I currently use taskwarrior (2) in termux)
