### ISSUE TITLE
Handle displaying URLs flexibly

### ISSUE THREAD

**Issue by srfraser** [GothenburgBitFactory/taskchampion#95]
Some URLs are very long, such as Google Docs links, and adding tasks that refer to those can make the report much wider and hard to read. 

I don't know the best way to deal with this. Some way to add links to a task which hides them or truncates them unless they're asked for, perhaps?  `task info` could show them, or new a subcommand like `task links` or `task details`

Brainstorming options:

1. If `project:` label syntax exists, add one for links
```
$ task add link:https://some.really.long.link/  description goes here
$ task list
…
 1         description goes here [links]
$ task info 1
[some output that includes urls]
``` 

2. `task list` recognising scheme:// formats and truncating them:

```
$ task add read this https://docs.google.com/document/d/AAAAA
$ task list
 id act description
 1         read this docs.google…
```

3. Option 2 but fetch the page title if possible

**Comment by djmitche** [comment]
I have this issue, too!  Finding a fix would be great.  I do often click on links in the terminal, so I'd want them displayed sometimes, but not always..

**Comment by savchenko** [comment]
How about trimming URL after the TLD with `...` and wrapping it in OSC-8 before passing to terminal?

**Comment by djmitche** [comment]
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda -- very cool!

**Comment by dbr** [comment]
For dumb terminals where colouring and escape codes aren't supported, a simple fallback might be to use footnote-style references to links:

```
$ task add read this https://docs.google.com/document/d/AAAAA
$ task list
 id act description
 1         read this [url#1]
 2         another task

[url#1]: https://docs.google.com/document/d/AAAAA
```

I also like the idea of `task add link:https://some.really.long.link/  description goes here` - it would give other TC interfaces (e.g a GUI) good options to nicely present links in a structured way

**Comment by djmitche** [comment]
A `link` attribute sounds like a great idea!

**Comment by savchenko** [comment]
Added to [v0.8.0](https://github.com/taskchampion/taskchampion/milestone/5).
